import { makeStyles } from '@mui/styles';
import colors from '../../lib/colors';
export default makeStyles((theme) => ({
  container_banner: {
    maxWidth: 1200,
    margin: 'auto auto',
    paddingTop: 24,
  },
  container_body_banner: {
    display: 'flex',
    width: '100%',
    justifyContent: 'space-between',
  },
  slider_body_banner: {
    'slick-list': {
      height: 350,
    },
  },
  left_body_banner: {
    width: '60%',
    height: 350,
  },
  right_body_banner: {
    width: '39%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    position: 'relative',
  },
  item_slick_slider_left_banner: {
    backgroundColor: 'F3E9E5',
    borderRadius: 2,
    height: 350,
    padding: 50,
  },
  content_slick_slider_banner: {
    width: '50%',
  },
  title_slick_slider_banner: {},
  sub_slick_slider_banner: {
    fontStyle: 'italic !important',
    marginBottom: '16px !important',
  },
  btn_slick_slider: {
    padding: '8px 16px',
    backgroundColor: colors.green,
    borderRadius: 2,
    width: 'fit-content',
    cursor: 'pointer',
  },
  text_btn_slick_slider: {
    color: colors.white,
  },
  item_voucher_right_banner: {
    width: '100%',
    borderRadius: 16,
    position: 'relative',
    boxShadow: '0 1px 15px 0 rgb(0 0 0 / 10%)',
  },
  badge_voucher: {
    position: 'absolute',
    right: 20,
    top: -10,
    padding: '4px 8px',
    backgroundColor: colors.white,
  },
  text_badge_voucher: {
    fontStyle: 'italic !important',
    color: colors.gray,
  },
  body_item_voucher: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: 16,
  },
  body_left_item_voucher: {
    display: 'flex',
    width: '70%',
  },
  body_right_item_voucher: {
    width: '30%',
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
    alignItems: 'center',
  },
  img_item_voucher: {
    width: 130,
    height: 130,
    borderRadius: 2,
    marginRight: 8,
  },
  time_voucher: {
    display: 'flex',
    alignItems: 'center',
  },
  item_time_voucher: {
    padding: '8px 8px',
    backgroundColor: colors.orange,
    borderRadius: 4,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  mask_item_voucher: {
    position: 'absolute',
    bottom: 1,
    opacity: 0.5,
    zIndex: 99,
    height: 40,
    width: '100%',
    borderBottomLeftRadius: 2,
    borderBottomRightRadius: 2,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    background: `linear-gradient(to top, #FFEFE2, ${colors.white})`,
    padding: '1px',
  },
  mask_text_item_voucher: {
    position: 'absolute',
    bottom: 1,
    zIndex: 99,
    height: 40,
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '1px',
  },
  circle1: {
    backgroundColor: '#f8f9fa !important',
    width: '20px !important',
    height: '20px',
    // borderRadius: ' 50%',
    position: 'absolute',
    top: '0px',
    transform: 'translateY(-50%)',
    zIndex: 999,
    right: '25%',
    borderBottomRightRadius: '50%',
    borderBottomLeftRadius: '50%',
    // boxShadow: '0 1px 15px 0 rgb(0 0 0 / 10%)',
  },
  circle2: {
    backgroundColor: '#f8f9fa',
    width: '20px',
    height: '20px',
    borderRadius: ' 50%',
    position: 'absolute',
    bottom: '-20px',
    transform: 'translateY(-50%)',
    zIndex: 999,
    right: '25%',
  },
}));
