// lấy toàn bộ danh sách người dùng
export const START_QUERY = 'START_QUERY';
export const END_QUERY = 'END_QUERY';

export const GET_ALL_EVALUATE_SUCCESS = 'GET_ALL_EVALUATE_SUCCESS';
export const GET_ALL_EVALUATE_FAIL = 'GET_ALL_EVALUATE_FAIL';
export const GET_ALL_EVALUATE_ADMIN_SUCCESS = 'GET_ALL_EVALUATE_ADMIN_SUCCESS';
export const GET_ALL_EVALUATE_ADMIN_FAIL = 'GET_ALL_EVALUATE_ADMIN_FAIL';
export const GET_ALL_EVALUATE_ADMIN_ACCOUNT_SUCCESS =
  'GET_ALL_EVALUATE_ADMIN_ACCOUNT_SUCCESS';
export const GET_ALL_EVALUATE_ADMIN_ACCOUNT_FAIL =
  'GET_ALL_EVALUATE_ADMIN_ACCOUNT_FAIL';
export const GET_EVALUATE_PAGE_SUCCESS = 'GET_EVALUATE_PAGE_SUCCESS';
export const GET_EVALUATE_PAGE_FAIL = 'GET_EVALUATE_PAGE_FAIL';
export const GET_EVALUATE_DETAIL_SUCCESS = 'GET_EVALUATE_DETAIL_SUCCESS';
export const GET_EVALUATE_DETAIL_FAIL = 'GET_EVALUATE_DETAIL_FAIL';
export const SEARCH_EVALUATE_SUCCESS = 'SEARCH_EVALUATE_SUCCESS';
export const SEARCH_EVALUATE_FAIL = 'SEARCH_EVALUATE_FAIL';
export const POST_EVALUATE_SUCCESS = 'POST_EVALUATE_SUCCESS';
export const POST_EVALUATE_FAIL = 'POST_EVALUATE_FAIL';
export const PUT_EVALUATE_SUCCESS = 'PUT_EVALUATE_SUCCESS';
export const PUT_EVALUATE_FAIL = 'PUT_EVALUATE_FAIL';
export const DELETE_EVALUATE_SUCCESS = 'DELETE_EVALUATE_SUCCESS';
export const DELETE_EVALUATE_FAIL = 'DELETE_EVALUATE_FAIL';
export const CLOSE_EVALUATE = 'CLOSE_EVALUATE';
